export const GET_KART_PRODUCTS = "GET_KART_PRODUCTS";
export const ADD_PRODUCT_TO_KART = "ADD_PRODUCT_TO_KART";
export const REMOVE_PRODUCT_FROM_KART = "REMOVE_PRODUCT_FROM_KART";
export const BUY_PRODUCTS_FROM_KART = "BUY_PRODUCTS_FROM_KART";
export const GET_MY_PRODUCTS = "GET_MY_PRODUCTS";
export const GET_STORE_PRODUCTS = "GET_MY_PRODUCTS";